### ISSUE TITLE
Texture does not update when removing vertices/triangles

### ISSUE THREAD

**Issue by daniCh8** [isl-org/Open3D#4400]
Hello,

I am trying to modify a mesh by removing some of its vertices; however, the texture and triangle uv do not update when doing so. Therefore, no material or texture is in the output when saving the modified mesh.

To reproduce the problem, you can use [this skull mesh](https://free3d.com/3d-model/skull-v3--785914.html) I found online ([files are attached to the issue](https://github.com/isl-org/Open3D/files/7688868/skull_obj.zip)):
<img width="262" alt="skull_model_picture" src="https://user-images.githubusercontent.com/48253372/145484844-c712a9d8-6344-49f4-a0ca-1340c289d0a5.png">

Here is the code to reproduce the issue:
```python
import open3d as o3d
import numpy as np

skull_path = <path_to_obj>
skull_o3d = o3d.io.read_triangle_mesh(skull_path, True)

random_drop = np.random.choice(len(skull_o3d.vertices), 20000, replace=False)
skull_o3d.remove_vertices_by_index(random_drop)

save_path = <save_path_for_modified_obj>
o3d.io.write_triangle_mesh(save_path, skull_o3d, write_triangle_uvs=True)
```
You will see that this code only outputs an obj file and no mtl or texture file. The texture of it is blank when I try to load the mesh, obviously:
<img width="342" alt="output_blank_mesh" src="https://user-images.githubusercontent.com/48253372/145484957-d98301f2-36e3-4435-a854-ff44d07591ff.png">

I have also tried to set the new attributes manually to obtain an updated texture, but it didn't work. Here is the code:
```python
import open3d as o3d
import numpy as np

def triangle_not_in_interception(tri, keys):
    return tri[0] in keys or tri[1] in keys or tri[2] in keys


def get_drop_indices_meshes(np_mesh, keys):
    to_drop = []
    keys = set(keys)
    
    for i, xyz in enumerate(np_mesh):
        if triangle_not_in_interception(xyz, keys):
            to_drop.append(i)
            
    return to_drop


skull_path = <path_to_obj>
skull_o3d = o3d.io.read_triangle_mesh(skull_path, True)

random_drop = np.random.choice(len(skull_o3d.vertices), 20000, replace=False)
tris = np.asarray(skull_o3d.triangles)
drop_tris = get_drop_indices_meshes(tris, random_drop)

localized_verts = np.delete(np.asarray(skull_o3d.vertices), random_drop, axis=0)
localized_tris = np.delete(np.asarray(skull_o3d.triangles), drop_tris, axis=0)
localized_triangles_ids = np.delete(np.asarray(skull_o3d.triangle_material_ids), drop_tris, axis=0)
drop_uvs = np.array([[x*3, x*3+1, x*3+2] for x in drop_tris]).ravel()
localized_triangles_uvs = np.delete(np.asarray(skull_o3d.triangle_uvs), drop_uvs, axis=0)

skull_o3d.vertices = o3d.utility.Vector3dVector(localized_verts)
skull_o3d.triangles = o3d.utility.Vector3iVector(localized_tris)
skull_o3d.triangle_uvs = o3d.utility.Vector2dVector(localized_triangles_uvs)
skull_o3d.triangle_material_ids = o3d.utility.IntVector(localized_triangles_ids)

save_path = <save_path_for_modified_obj>
o3d.io.write_triangle_mesh(save_path, skull_o3d, write_triangle_uvs=True)
```

This code indeed manages to output an mtl and texture file, but they are not working when I try to load them in any 3d editor. Here is the error when I try to load the textured mesh in blender:
<img width="709" alt="textured_mesh_blender_error" src="https://user-images.githubusercontent.com/48253372/145485057-efa2886e-5527-48bf-ba59-4dac9cd18267.png">

Thank you in advance for your help!

**Comment by Gregory1994** [comment]
Same question, Have you find any solution? @theNded Thank you!

**Comment by daniCh8** [comment]
Hello @Gregory1994; no news on this from my side, unfortunately. Let me know if you find anything.

**Comment by errissa** [comment]
@daniCh8 The problem was not with the IO but with `remove_vertices_by_index` which was not adjusting the UVs after the vertices and associated triangles were removed. This is now addressed by PR #4443 . I modified your script to remove fewer vertices (made the problem more obvious to me) and to visualize the results. Please give the PR a try and let me know if it doesn't solve the problem for you.

**Comment by daniCh8** [comment]
@errissa yes, sorry, I did notice that the problem was there but didn't phrase the question correctly. Anyways, great job with this! It's working properly now. I'm closing this issue because it's fixed.

**Comment by tillns** [comment]
Hi
I just noticed that the triangle UVs are indeed correctly updated. However, the triangle material IDs are not updated. The array stays the same length after removing some vertices/triangles. It should be easy to update that array as well using the same triangle mask, I hope. 
Cheers

**Comment by mohamad-hasan-sohan-ajini** [comment]
Hey

I'm here for the same issue. It seems that the issue persists in version `0.17.0`. In my case the issue is solved by calling `skull_o3d.compute_vertex_normals()` after `skull_o3d.remove_vertices_by_index(random_drop)`. Please let me know it worked for you @tillns @daniCh8 
Regards

**Comment by mohamad-hasan-sohan-ajini** [comment]
Hey

I'm here for the same issue. It seems that the issue persists in version 0.17.0. In my case the issue is solved by calling `skull_o3d.compute_vertex_normals()` after `skull_o3d.remove_vertices_by_index(random_drop)`. Please let me know it worked for you @tillns @daniCh8

P.S. Please check if setting `enable_post_processing` to `False` affects the results. Setting it to False made that work!

Regards
