### ISSUE TITLE
Inconsistent Rotation Matrix for Bounding Boxes

### ISSUE THREAD

**Issue by TheDech** [isl-org/Open3D#4716]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am detecting bounding boxes from a point cloud after clustering and noticed after visualizing the bounding boxes and their respective frames that some had Z-axis pointing down and others pointing up.
Is the way the rotation matrix is extracted correct?
I can't share the point cloud itself but can share the code used and an snapshot of all bounding boxes obtained.
Also the option **robust** for `get_oriented_bounding_box()` is not available in this case, is there a way to use it?

![Screenshot from 2022-02-07 17-48-13](https://user-images.githubusercontent.com/53280333/152903009-9d8c65ab-15ec-449f-acff-c9734081df47.png)
![Screenshot from 2022-02-07 17-48-24](https://user-images.githubusercontent.com/53280333/152903011-d6e013b9-e1be-4b5f-97c4-31f99f6bd0c8.png)

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np
from scipy.spatial.transform import Rotation as R

# Read pointCloud
pcd = o3d.io.read_point_cloud(path_to_ply)

# DBSCAN Clustering
with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm:
     labels = np.array(self.pcd.cluster_dbscan(eps=self.eps, min_points=self.num_pts, print_progress=True))

for i in range(labels.max()+1):
     # id is array of point names in main point cloud, owned by cluster with label i
     id = np.where(labels == i)[0]
     pcd_i = self.pcd.select_by_index(id)
     obb = pcd_i.get_oriented_bounding_box()
     obb.color = (0,1,0)
     mesh_r = o3d.geometry.TriangleMesh.create_coordinate_frame(0.04,origin = obb.get_center())
     mesh_r.rotate(obb.R, obb.get_center())
     o3d.visualization.draw_geometries([pcd, obb, mesh_r])
```

### Expected behavior

The frame should have z-axis pointing down.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 18.04
- Python version: (e.g. Python 3.8 / output from `import sys  print(sys.version)`)
- Open3D version: python 3.6.9
- System type: x84
- Is this remote workstation?: yes
- How did you install Open3D?: pip and build from source
- Compiler version (if built from source): gcc 8.4
```

**Comment by benjaminum** [comment]
Can you check `import open3d; print(open3d.__version__)`?

**Comment by benjaminum** [comment]
Please try the development wheel. It has some bugfixes related to the oriented bounding box.

**Comment by benjaminum** [comment]
We have released version 0.15, which has bugfixes for the oriented bounding box.

**Comment by pieterblok** [comment]
@benjaminum sorry to bother you. 

I have tried the same approach as @TheDech, with and without activating the robust option in get_oriented_bounding_box, but the coordinate frames (made from the rotation matrix of the bounding box) are still not consistent. 

My open3d version is 0.15.2

**Comment by benjaminum** [comment]
@pieterblok Do you have a minimal example to reproduce the problem?

**Comment by L-Reichardt** [comment]
Problem still persists, even with newest version. Oriented Bounding box is still extremely buggy and barely useable for the rotation matrix.

**Comment by pieterblok** [comment]
> @pieterblok Do you have a minimal example to reproduce the problem?

@benjaminum yes, consider the following situation: I have captured four RGB-D images from the same object (a pear) and from the same camera position. See the following setup:
![IMG_5941](https://user-images.githubusercontent.com/40503128/211999673-ff0d8a84-f9bf-4084-8731-e89efd4ba23e.jpeg)

When I process the four frames, each time a different rotation matrix is resulted from the oriented bounding box:
point cloud 01: https://drive.google.com/file/d/10rX5sdYagToNrjelgARqOUXlYtCCUB71/view?usp=sharing
point cloud 02: https://drive.google.com/file/d/1ZDl08yGcJ1rac4WQb3_4EbmAhAw1SDRa/view?usp=sharing
point cloud 03: https://drive.google.com/file/d/1W6ngpKJTh3SPPUJh1lyDG2N6tliSpyvO/view?usp=sharing
point cloud 04: https://drive.google.com/file/d/1GnW17NBMpbURgj_L82V2CTMxH7Z842LN/view?usp=sharing

This is the code:
```python
import open3d as o3d
import numpy as np

center_points = [[-0.01135033, 0.01374012, -0.444], 
                [-0.01140146, 0.01380201, -0.446],
                [-0.01137589, 0.01426044, -0.445],
                [-0.01135033, 0.01422839, -0.444]]

for i in range(len(center_points)):
    pcd = o3d.io.read_point_cloud("pear_0{:d}.pcd".format(i+1))
    bb = pcd.get_oriented_bounding_box(robust=False)
    bb.color = np.array([1, 0, 0])
    mesh = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.05, origin=center_points[i])
    mesh.rotate(bb.R, center=center_points[i])
    o3d.visualization.draw_geometries([pcd, bb, mesh])
```

My open3d version is 0.15.2, and activating or deactivating the 'robust' option doesn't improve this.

**Comment by benjaminum** [comment]
I see. The orientation is not temporally stable. 
Unfortunately `get_oriented_bounding_box()` does not guarantee this. Internally it uses PCA to estimate the axes of the bounding box and the sign may change.

As a workaround you could take the first OBB orientation as a reference and then permute the axes of the subsequent OBBs until you find the one that has the smallest rotation angle to the previous one.

**Comment by pieterblok** [comment]
> I see. The orientation is not temporally stable. Unfortunately `get_oriented_bounding_box()` does not guarantee this. Internally it uses PCA to estimate the axes of the bounding box and the sign may change.
> 
> As a workaround you could take the first OBB orientation as a reference and then permute the axes of the subsequent OBBs until you find the one that has the smallest rotation angle to the previous one.

@benjaminum thank you for your fast response!

Regarding the axes and the order of the corner points of the OBB: are these always constructed in the same way? 

The following 4 figures show the order of the corner points, and based on this information, I can rotate the OBB in case the points do not correspond to what I would expect. Refer that the blue part of the OBB is the detected top of the object (the top represents the stem where the pear grows on the tree, if a pear grows upside down, then the blue part is at the bottom). 

Point cloud 01 (scenario 1):
![rotation_matrix_scenario_01_bb_corner_points](https://user-images.githubusercontent.com/40503128/212599396-04faaca8-a9cb-425f-8232-2ab563aadbe8.png)

Point cloud 02 (scenario 2):
![rotation_matrix_scenario_02_bb_corner_points](https://user-images.githubusercontent.com/40503128/212599533-c6280ab8-68c8-43a3-8b78-c75bd764b46a.png)

Point cloud 03 (scenario 3):
![rotation_matrix_scenario_03_bb_corner_points](https://user-images.githubusercontent.com/40503128/212599549-9b7228ad-ad17-43a4-8da4-5ec728a0e700.png)

Point cloud 04 (scenario 4):
![rotation_matrix_scenario_04_bb_corner_points](https://user-images.githubusercontent.com/40503128/212599586-35165878-f61f-426e-89e0-789a082c00c0.png)

Hypothesizing on a pseudo-code of a potential work-around (in which cp is a corner point of the OBB and blue is the blue part of the OBB):
```python
## scenario 1 represents the desired rotation matrix
if cp0 in blue and cp2 in blue and cp3 in blue and cp5 in blue:

  ## calculate the 3D Euclidean distance (dist) between the corner points on the camera plane
  if dist(cp0, camera) < dist(cp3, camera) and dist(cp2, camera) < dist(cp5, camera):
    bb.R = bb.R ## scenario 1
  else:
    bb.R = bb.R * np.asarray([[1, -1, 1], [1, -1, -1], [1, 1, -1]]) ## scenario 3
else:
  if dist(cp0, camera) < dist(cp3, camera) and dist(cp2, camera) < dist(cp5, camera):
    bb.R = bb.R * np.asarray([[-1, -1, 1], [-1, -1, 1], [1, -1, 1]]) ## scenario 4
  else:
    bb.R = bb.R * np.asarray([[-1, 1, -1], [-1, 1, -1], [-1, 1, -1]]) ## scenario 2
```

This solution obviously only works if the order of the corner points of the OBB are consistent. Differently put: do you know when the rotation matrix is in scenario 1, that corner point 0 is always top-right closest to the camera, corner point 2 is always top-left closest to the camera etc.? If so, the pseudo-code above would work...

Thanks in advance!

**Comment by benjaminum** [comment]
The points are generated from the rotations matrix so they should be consistent

**Comment by pieterblok** [comment]
> The points are generated from the rotations matrix so they should be consistent

Ok, thanks, then I should continue with this approach...

**Comment by AwokeKnowing** [comment]
I am running into this issue. i have 0.17    my visualization flips randomly because i use the orientation box as the source of a rotation matrix to align a plane to be flat with the ground.

can you clarify how i can ensure the orientation of the box? it seems we could give it orientation_reference like we do for normals.

**Comment by Lokesh-26** [comment]
> Closing this issue. Please comment if this should be reopened.

Hi @benjaminum,
  I want to compute a mesh arrow that points at the edge of the OBB of a object for robot grasping. But due to the inconsistent axis, it is difficult to compute the mesh arrow at the desired point. Is there any solution to make the axis consistent? It would be really helpful :)

**Comment by benjaminum** [comment]
There is unfortunately no solution to this as there is no absolute reference

**Comment by SMohammadi89** [comment]
> > I see. The orientation is not temporally stable. Unfortunately `get_oriented_bounding_box()` does not guarantee this. Internally it uses PCA to estimate the axes of the bounding box and the sign may change.
> > As a workaround you could take the first OBB orientation as a reference and then permute the axes of the subsequent OBBs until you find the one that has the smallest rotation angle to the previous one.
> 
> @benjaminum thank you for your fast response!
> 
> Regarding the axes and the order of the corner points of the OBB: are these always constructed in the same way?
> 
> The following 4 figures show the order of the corner points, and based on this information, I can rotate the OBB in case the points do not correspond to what I would expect. Refer that the blue part of the OBB is the detected top of the object (the top represents the stem where the pear grows on the tree, if a pear grows upside down, then the blue part is at the bottom).
> 
> Point cloud 01 (scenario 1): ![rotation_matrix_scenario_01_bb_corner_points](https://user-images.githubusercontent.com/40503128/212599396-04faaca8-a9cb-425f-8232-2ab563aadbe8.png)
> 
> Point cloud 02 (scenario 2): ![rotation_matrix_scenario_02_bb_corner_points](https://user-images.githubusercontent.com/40503128/212599533-c6280ab8-68c8-43a3-8b78-c75bd764b46a.png)
> 
> Point cloud 03 (scenario 3): ![rotation_matrix_scenario_03_bb_corner_points](https://user-images.githubusercontent.com/40503128/212599549-9b7228ad-ad17-43a4-8da4-5ec728a0e700.png)
> 
> Point cloud 04 (scenario 4): ![rotation_matrix_scenario_04_bb_corner_points](https://user-images.githubusercontent.com/40503128/212599586-35165878-f61f-426e-89e0-789a082c00c0.png)
> 
> Hypothesizing on a pseudo-code of a potential work-around (in which cp is a corner point of the OBB and blue is the blue part of the OBB):
> 
> ```python
> ## scenario 1 represents the desired rotation matrix
> if cp0 in blue and cp2 in blue and cp3 in blue and cp5 in blue:
> 
>   ## calculate the 3D Euclidean distance (dist) between the corner points on the camera plane
>   if dist(cp0, camera) < dist(cp3, camera) and dist(cp2, camera) < dist(cp5, camera):
>     bb.R = bb.R ## scenario 1
>   else:
>     bb.R = bb.R * np.asarray([[1, -1, 1], [1, -1, -1], [1, 1, -1]]) ## scenario 3
> else:
>   if dist(cp0, camera) < dist(cp3, camera) and dist(cp2, camera) < dist(cp5, camera):
>     bb.R = bb.R * np.asarray([[-1, -1, 1], [-1, -1, 1], [1, -1, 1]]) ## scenario 4
>   else:
>     bb.R = bb.R * np.asarray([[-1, 1, -1], [-1, 1, -1], [-1, 1, -1]]) ## scenario 2
> ```
> 
> This solution obviously only works if the order of the corner points of the OBB is consistent. Differently put: do you know when the rotation matrix is in scenario 1, that corner point 0 is always top-right closest to the camera, corner point 2 is always top-left closest to the camera etc.? If so, the pseudo-code above would work...
> 
> Thanks in advance!

Hi, did you resolve the issue? If yes, could you please release the full code?

**Comment by pieterblok** [comment]
This is a very specific situation optimized for the pears. I guess it has to be finetuned for your specific 3D boxes, as those are different.

**Comment by pieterblok** [comment]
> @pieterblok, thank you for the response. The object that I use is a box and I am facing the same problem where the order of the corner of the bounding box are changing and also the orientation. I would like to have the same bounding orientation as point cloud and fix corner order.
> 
> 
> 
> Thanks again for helping 

I'll share my code tomorrow, but the point I want to make: I'm not sure if it makes sense given your specific situation.

**Comment by pieterblok** [comment]
> > @pieterblok, thank you for the response. The object that I use is a box and I am facing the same problem where the order of the corner of the bounding box are changing and also the orientation. I would like to have the same bounding orientation as point cloud and fix corner order.
> > Thanks again for helping
> 
> I'll share my code tomorrow, but the point I want to make: I'm not sure if it makes sense given your specific situation.

Below is the specific function in Python:
```python
## bug-fix for the incorrect rotation matrix of the oriented bounding box
def rotate_bouding_box(bb, smallest_ids):
    bbp = np.asarray(bb.get_box_points())
    if 0 in smallest_ids[0:4] and 2 in smallest_ids[0:4] and 3 in smallest_ids[0:4] and 5 in smallest_ids[0:4]:
        ## scenario-01
        if (abs(bbp[0][2]) < abs(bbp[3][2])) and (abs(bbp[0][2]) < abs(bbp[3][2])):
            bb.R = bb.R * np.asarray([[-1, 1, -1], [-1, 1, -1], [-1, 1, -1]])
        ## scenario-03
        if (abs(bbp[0][2]) > abs(bbp[3][2])) and (abs(bbp[0][2]) > abs(bbp[3][2])):
            bb.R = bb.R * np.asarray([[-1, -1, 1], [-1, -1, 1], [-1, -1, 1]])
    else:
        ## scenario-04
        if (abs(bbp[0][2]) < abs(bbp[3][2])) and (abs(bbp[0][2]) < abs(bbp[3][2])):
            bb.R = bb.R * np.asarray([[1, -1, 1], [1, -1, -1], [1, 1, -1]])
        ## scenario-02
        if (abs(bbp[0][2]) > abs(bbp[3][2])) and (abs(bbp[0][2]) > abs(bbp[3][2])):
            bb.R = bb.R
    return bb
```

This is the reduced context, but I'm not sure if it makes sense to you:
```python
for rgb_image, depth_image in zip(rgbimages, depthimages):
    ## Load images
    color_image = cv2.imread(os.path.join(config['image_folder'], rgb_image))
    depth_image = cv2.imread(os.path.join(config['image_folder'], depth_image), -1)
  
    ## Deep-learning analysis
    outputs = predictor(color_image)    
    instances = outputs["instances"].to("cpu")
    masks = instances.pred_masks.numpy()
    
    for i in range(masks.shape[0]):
        mask = masks[i,:,:]
        mask_img = np.multiply(mask.astype(np.uint8), 255)
  
        ## remove the small objects (using the config['minimal_pixel_area'])
        contours_unfiltered, _ = cv2.findContours(mask_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
        mask_img = np.zeros((mask.shape[0], mask.shape[1])).astype(np.uint8)
        for cnts in range(len(contours_unfiltered)):
            area = cv2.contourArea(contours_unfiltered[cnts])
            if area > config['minimal_pixel_area']:
                cv2.fillPoly(mask_img, [contours_unfiltered[cnts]], 255)
  
        mask = mask_img.astype(np.bool)
        contours, _ = cv2.findContours(mask_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
  
        if len(contours) > 0:
            cnts = np.concatenate(contours)
            bbx,bby,bbw,bbh = cv2.boundingRect(cnts)
            
         M = cv2.moments(cnts)
         cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])
            
            ## calculate the largest distance from the estimated keypoint (assuming this is the pear attachment to the tree)
            extLeft = cnts[cnts[:, :, 0].argmin()][0]
            extRight = cnts[cnts[:, :, 0].argmax()][0]
            extTop = cnts[cnts[:, :, 1].argmin()][0]
            extBot = cnts[cnts[:, :, 1].argmax()][0]
  
            largest_dist = 0
            for extPoint in zip([extLeft, extRight, extTop, extBot]):
                dist = np.linalg.norm(extPoint[0] - (int(cX), int(cY)))
                if dist > largest_dist:
                    most_extended_point = extPoint[0]
                    largest_dist = dist
  
            ## remove the depth outliers via histogram filtering
            img_mask = np.multiply(color_image, np.expand_dims(mask, axis=2))
            dimg_mask = np.multiply(depth_image, mask)
            dimg_mask_vis = dimg_mask.astype(np.uint8)
  
            nmY, nmX = statistics.nearest_nonzero_idx(dimg_mask, most_extended_point[1], most_extended_point[0])
            xyzm = statistics.pixel_to_point(config['intrinsics_file'], [nmX, nmY], dimg_mask[nmY, nmX], config['realsense_type'])
            xyzm = xyzm/config['depth_scale']
  
            ## load the rgb and depth masks and make an open3d pointcloud
            rgb_mask = o3d.geometry.Image((img_mask[:,:,::-1]).astype(np.uint8))
            depth_mask = o3d.geometry.Image(dimg_mask)
            rgbd_mask = o3d.geometry.RGBDImage.create_from_color_and_depth(rgb_mask, depth_mask, depth_scale=config['depth_scale'], depth_trunc=config['depth_trunc'], convert_rgb_to_intensity=False)
            pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_mask, intrinsics)
            
            ## transform the pointcloud and do some filtering
            cl, ind = pcd.remove_statistical_outlier(nb_neighbors=config['number_neighbors'], std_ratio=config['std_ratio'])
            cl.remove_non_finite_points(remove_nan=True, remove_infinite=True)
  
            try:
                bb = cl.get_oriented_bounding_box(robust=False)
                bb.color = np.array([1, 0, 0])
  
                ## determine the pear turning point (the most extended side of the oriented bounding box)
                bbp = np.asarray(bb.get_box_points())
                dists_3d = []
                for p in range(bbp.shape[0]):
                    dist = np.linalg.norm(xyzm - bbp[p])
                    dists_3d.append(dist)
                line_points = []
                smallest_ids = [k[0] for k in sorted(enumerate(dists_3d), key=lambda x:x[1])]
                for si in range(4):
                    line_points.append(bbp[smallest_ids[si]])
  
                comb = list(combinations(range(4), 2))
                line_set = o3d.geometry.LineSet()
                line_set.points = o3d.utility.Vector3dVector(line_points)
                line_set.lines = o3d.utility.Vector2iVector(comb)
                colors = [[0, 0, 1] for _ in range(len(comb))]
                line_set.colors = o3d.utility.Vector3dVector(colors)
  
                ## bug-fix for the incorrect rotation matrix of the oriented bounding box
                bb = o3d_utils.rotate_bouding_box(bb, smallest_ids)
```
